INSERT INTO BOOK (bookid, booktitle, bookauthor, bookgenre, booklanguage) VALUES 
(1, 'An Enchantment of Ravens', 'Margaret Rogerson', 'Young Adult Fantasy / Romance', 'English'),
(2, 'Serpent & Dove', 'Shelby Mahurin', 'Young Adult Fantasy / Romance', 'English'),
(3, 'Blood & Honey', 'Shelby Mahurin', 'Young Adult Fantasy / Romance', 'English'),
(4, 'Gods & Monsters', 'Shelby Mahurin', 'Young Adult Fantasy / Romance', 'English'),
(5, 'The Cruel Prince', 'Holly Black', 'Young Adult Fantasy / Dark Fantasy', 'English'),
(6, 'The Wicked King', 'Holly Black', 'Young Adult Fantasy / Political Intrigue', 'English'),
(7, 'The Queen of Nothing', 'Holly Black', 'Young Adult Fantasy / Romance', 'English'),
(8, 'You’ve Reached Sam', 'Dustin Thao', 'Young Adult Contemporary / Magical Realism', 'English'),
(9, 'A Winter’s Promise', 'Christelle Dabos', 'Young Adult Fantasy / Steampunk', 'English'),
(10, 'The Missing of Clairdelune', 'Christelle Dabos', 'Young Adult Fantasy / Steampunk', 'English'),
(11, 'The Memory of Babel', 'Christelle Dabos', 'Young Adult Fantasy / Steampunk', 'English'),
(12, 'The Storm of Echoes', 'Christelle Dabos', 'Young Adult Fantasy / Steampunk', 'English'),
(13, 'The Cat Who Saved Books', 'Sosuke Natsukawa', 'Literary Fiction / Magical Realism', 'English'),
(14, 'The Seven Husbands Of Evelyn Hugo', 'Taylor Jenkins Reid', 'Historical Fiction / LGBTQ+ / Romance', 'English'),
(15, 'To Kill A Kingdom', 'Alexandra Christo', 'Young Adult Fantasy / Retelling', 'English'),
(16, 'These Violent Delights', 'Chloe Gong', 'Young Adult Historical Fantasy / Retelling', 'English'),
(17, 'House of Salt and Sorrows', 'Erin A. Craig', 'Young Adult Gothic Fantasy / Horror', 'English'),
(18, 'The TurnGlass', 'Gareth Rubin', 'Mystery / Thriller / Historical Fiction', 'English'),
(19, 'The Book That Wouldn’t Burn', 'Mark Lawrence', 'Fantasy / Sci-Fi / Philosophical Fiction', 'English'),
(20, 'Court Of The Vampire Queen', 'Katee Robert', 'Adult Paranormal Romance / Erotica', 'English')